name: Deploy Cloudflare Worker

on:
  push:
    paths:
      - 'workers/**'
      - 'wrangler.toml'
      - '.github/workflows/deploy-worker.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            BFL_API_KEY
            GS_WEBHOOK_URL
        env:
          BFL_API_KEY: ${{ secrets.BFL_API_KEY }}
          GS_WEBHOOK_URL: ${{ secrets.GS_WEBHOOK_URL }}
